services:
  4proj-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 4proj-front
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - 4proj-network

networks:
  4proj-network:
    external: true
